#!/usr/bin/env bash

echo 'Google'

adb shell pm uninstall --user 0 'com.android.bips'
adb shell pm uninstall --user 0 'com.android.bluetoothmidiservice'
adb shell pm uninstall --user 0 'com.android.bookmarkprovider'
adb shell pm uninstall --user 0 'com.android.chrome'
adb shell pm uninstall --user 0 'com.android.dreams.basic'
adb shell pm uninstall --user 0 'com.android.egg'
adb shell pm uninstall --user 0 'com.android.email.partnerprovider'
adb shell pm uninstall --user 0 'com.android.htmlviewer'
adb shell pm uninstall --user 0 'com.android.providers.partnerbookmarks'
adb shell pm uninstall --user 0 'com.android.sharedstoragebackup'
adb shell pm uninstall --user 0 'com.android.simappdialog'
adb shell pm uninstall --user 0 'com.android.stk'
adb shell pm uninstall --user 0 'com.android.storagemanager'
adb shell pm uninstall --user 0 'com.android.systemui.plugin.globalactions.wallet'
adb shell pm uninstall --user 0 'com.android.traceur'
adb shell pm uninstall --user 0 'com.android.wallpaper.livepicker'

adb shell pm uninstall --user 0 'com.google.ambient.streaming'
adb shell pm uninstall --user 0 'com.google.android.adservices.api'
adb shell pm uninstall --user 0 'com.google.android.apps.googleassistant'
adb shell pm uninstall --user 0 'com.google.android.apps.healthdata'
adb shell pm uninstall --user 0 'com.google.android.apps.restore'
adb shell pm uninstall --user 0 'com.google.android.apps.walletnfcrel'
adb shell pm uninstall --user 0 'com.google.android.apps.wellbeing'
adb shell pm uninstall --user 0 'com.google.android.apps.nbu.files'
adb shell pm uninstall --user 0 'com.google.android.as'
adb shell pm uninstall --user 0 'com.google.android.as.oss'
adb shell pm uninstall --user 0 'com.google.android.feedback'
adb shell pm uninstall --user 0 'com.google.android.googlequicksearchbox'
adb shell pm uninstall --user 0 'com.google.android.health.connect.backuprestore'
adb shell pm uninstall --user 0 'com.google.android.healthconnect.controller'
adb shell pm uninstall --user 0 'com.google.android.keep'
adb shell pm uninstall --user 0 'com.google.android.marvin.talkback'
adb shell pm uninstall --user 0 'com.google.android.onetimeinitializer'
adb shell pm uninstall --user 0 'com.google.android.partnersetup'
adb shell pm uninstall --user 0 'com.google.android.printservice.recommendation'
adb shell pm uninstall --user 0 'com.google.android.projection.gearhead'
adb shell pm uninstall --user 0 'com.google.android.tts'
adb shell pm uninstall --user 0 'com.google.android.setupwizard'
adb shell pm uninstall --user 0 'com.google.ar.core'
adb shell pm uninstall --user 0 'com.google.ar.lens'
adb shell pm uninstall --user 0 'com.google.mainline.adservices'
adb shell pm uninstall --user 0 'com.google.mainline.telemetry'

echo 'Meta'

adb shell pm uninstall --user 0 'com.facebook.appmanager'
adb shell pm uninstall --user 0 'com.facebook.services'
adb shell pm uninstall --user 0 'com.facebook.system'

echo 'Microsoft'

adb shell pm uninstall --user 0 'com.microsoft.appmanager'
adb shell pm uninstall --user 0 'com.microsoft.deviceintegrationservice'
adb shell pm uninstall --user 0 'com.microsoftsdk.crossdeviceservicebroker'
