#!/usr/bin/env bash

echo 'OPPO'

adb shell pm uninstall --user 0 'com.coloros.activation'
adb shell pm uninstall --user 0 'com.coloros.childrenspace'
adb shell pm uninstall --user 0 'com.coloros.compass2'
adb shell pm uninstall --user 0 'com.coloros.filemanager'
adb shell pm uninstall --user 0 'com.coloros.floatassistant'
adb shell pm uninstall --user 0 'com.coloros.gallery3d'
adb shell pm uninstall --user 0 'com.coloros.healthcheck'
adb shell pm uninstall --user 0 'com.coloros.karaoke'
adb shell pm uninstall --user 0 'com.coloros.ocs.opencapabil'
adb shell pm uninstall --user 0 'com.coloros.operationManual'
adb shell pm uninstall --user 0 'com.coloros.oshare'
adb shell pm uninstall --user 0 'com.coloros.phonemanager'
adb shell pm uninstall --user 0 'com.coloros.scenemode'
adb shell pm uninstall --user 0 'com.coloros.securepay'
adb shell pm uninstall --user 0 'com.coloros.smartsidebar'
adb shell pm uninstall --user 0 'com.coloros.soundrecorder'
adb shell pm uninstall --user 0 'com.coloros.video'
adb shell pm uninstall --user 0 'com.coloros.weather.service'
adb shell pm uninstall --user 0 'com.coloros.weather2'
adb shell pm uninstall --user 0 'com.debug.loggerui'
adb shell pm uninstall --user 0 'com.fintech.life'
adb shell pm uninstall --user 0 'com.glance.internet'
adb shell pm uninstall --user 0 'com.heytap.accessory'
adb shell pm uninstall --user 0 'com.heytap.browser'
adb shell pm uninstall --user 0 'com.heytap.market'
adb shell pm uninstall --user 0 'com.heytap.mcs'
adb shell pm uninstall --user 0 'com.heytap.music'
adb shell pm uninstall --user 0 'com.heytap.pictorial'
adb shell pm uninstall --user 0 'com.heytap.usercenter'
adb shell pm uninstall --user 0 'com.payjoy.access'
adb shell pm uninstall --user 0 'com.wapi.wapicertmanager'

adb shell pm uninstall --user 0 'com.oplus.account'
adb shell pm uninstall --user 0 'com.oplus.aiunit'
adb shell pm uninstall --user 0 'com.oplus.aod'
adb shell pm uninstall --user 0 'com.oplus.apprecover'
adb shell pm uninstall --user 0 'com.oplus.atlas'
adb shell pm uninstall --user 0 'com.oplus.bttestmode'
adb shell pm uninstall --user 0 'com.oplus.cast'
adb shell pm uninstall --user 0 'com.oplus.commercial'
adb shell pm uninstall --user 0 'com.oplus.cosa'
adb shell pm uninstall --user 0 'com.oplus.cota'
adb shell pm uninstall --user 0 'com.oplus.crashbox'
adb shell pm uninstall --user 0 'com.oplus.customize.coreapp'
adb shell pm uninstall --user 0 'com.oplus.encryption'
adb shell pm uninstall --user 0 'com.oplus.engineercamera'
adb shell pm uninstall --user 0 'com.oplus.engineermode'
adb shell pm uninstall --user 0 'com.oplus.engineernetwork'
adb shell pm uninstall --user 0 'com.oplus.games'
adb shell pm uninstall --user 0 'com.oplus.healthservice'
adb shell pm uninstall --user 0 'com.oplus.interconnectcollectkit'
adb shell pm uninstall --user 0 'com.oplus.lfeh'
adb shell pm uninstall --user 0 'com.oplus.linker'
adb shell pm uninstall --user 0 'com.oplus.logkit'
adb shell pm uninstall --user 0 'com.oplus.melody'
adb shell pm uninstall --user 0 'com.oplus.multiapp'
adb shell pm uninstall --user 0 'com.oplus.nas'
adb shell pm uninstall --user 0 'com.oplus.ocloud'
adb shell pm uninstall --user 0 'com.oplus.olc'
adb shell pm uninstall --user 0 'com.oplus.onet'
adb shell pm uninstall --user 0 'com.oplus.onetrace'
adb shell pm uninstall --user 0 'com.oplus.payjoy'
adb shell pm uninstall --user 0 'com.oplus.postmanservice'
adb shell pm uninstall --user 0 'com.oplus.qualityprotect'
adb shell pm uninstall --user 0 'com.oplus.screenrecorder'
adb shell pm uninstall --user 0 'com.oplus.smartengine'
adb shell pm uninstall --user 0 'com.oplus.statistics.rom'
adb shell pm uninstall --user 0 'com.oplus.synergy'
adb shell pm uninstall --user 0 'com.oplus.themestore'
adb shell pm uninstall --user 0 'com.oplus.viewtalk'
adb shell pm uninstall --user 0 'com.oplus.wifibackuprestore'
adb shell pm uninstall --user 0 'com.ses.entitlement.o2'

adb shell pm uninstall --user 0 'com.oppo.quicksearchbox'

adb shell pm uninstall --user 0 'com.realme.movieshot'
adb shell pm uninstall --user 0 'com.realme.wellbeing'

echo 'MediaTek'

adb shell pm uninstall --user 0 'com.Btek.engineermode'
adb shell pm uninstall --user 0 'com.Btek.omacp'
adb shell pm uninstall --user 0 'com.Btek.voicecommand'

echo 'Tencent'

adb shell pm uninstall --user 0 'com.tencent.soter.soterserver'
